### ISSUE TITLE
Create add an intent from Settings button to a new page

### ISSUE THREAD

**Issue by maryehuerta** [idappthat/Sloth#17]
<img width="288" alt="screen shot 2019-02-08 at 6 56 35 pm" src="https://user-images.githubusercontent.com/22576130/52513928-ac47ef00-2bd3-11e9-8cce-362675793a34.png">

<img width="289" alt="screen shot 2019-02-08 at 6 56 41 pm" src="https://user-images.githubusercontent.com/22576130/52513931-ae11b280-2bd3-11e9-8b6d-f3890a581c02.png">

Once you click on "Settings" bring the user to a new page called settings

**Comment by hjpatel16** [comment]
Hi, Can I work on it?
