### ISSUE TITLE
View above keyboard on note creation fragment in EditorFragment

### ISSUE THREAD

**Issue by kels-c** [idappthat/Sloth#2]
[Example](https://i2.wp.com/ioshacker.com/wp-content/uploads/2016/11/Bear-app-1.jpg?resize=610%2C533)

**Comment by kels-c** [comment]
As discussed, possibly a horizontal [RecyclerView](https://stackoverflow.com/questions/28460300/how-to-build-a-horizontal-listview-with-recyclerview) and accounting for when [keyboard](https://stackoverflow.com/questions/1964789/move-layouts-up-when-soft-keyboard-is-shown) is hidden/visible. Decide behavior on both.

**Comment by AlexPavlak** [comment]
Horizontal recycler view figured out(just takes one change to a standard recycler view). Need to work on using buttons and inserting text when pressed next.
